### ISSUE TITLE
Glossary of terms

### ISSUE THREAD

**Issue by abankston-policy** [JMMaok/postdoc#21]
https://docs.google.com/spreadsheets/d/1F7-cnP_pN1n7GV_AeOpt4EtPJ91OaUDujrmDVBdYyfc/edit#gid=1881037537 (second tab)

**Comment by JMMaok** [comment]
Duplicate of #19

**Comment by JMMaok** [comment]
Thank you, Adriana! I am moving this to the category Supplementary Material (issue #19)
